#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'lights' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts INTEGER n as parameter.
#

def lights(n):
    # Write your code here
    return (2**n-1)%100000
        
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        result = lights(n)

        fptr.write(str(result) + '\n')

    fptr.close()
    
    
    #The solution should give all the possibilities except for when all the lights are closed. This can also be done by factorial method: 
    if 4 lights were there; 4C4 + 4C3 + 4C2 + 4C1
